/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ict.test.paul;

import ict.bean.*;
import ict.db.*;

/**
 *
 * @author Tong
 */
public class TestClinicAddRecord {

    public static void main(String[] arg) {
        String url = "jdbc:mysql://localhost:3306/ITP4511_Assignment_DB";
        String username = "root";
        String password = "";
        ClinicDB clinicDB = new ClinicDB(url, username, password);
        ClinicBean cb = new ClinicBean(
                0, // clinicId will be auto-generated by the database
                "Happy Paws Veterinary Clinic",
                "123 Pet Street, Animal City",
                java.sql.Time.valueOf("09:00:00"),
                java.sql.Time.valueOf("18:00:00"),
                true
        );
        clinicDB.addRecord(cb);
    }
}
